#!/usr/bin/env node
// Shipped with WormHole v0.1.0. See workspace/tools/TOOLS.md for usage.
//
/**
 * compact-session.js
 *
 * Compress old turns of a WormHole session JSONL into a single summary turn,
 * keeping the most recent N turns intact. Summary is generated by a local
 * Ollama model (default gemma4:26b) at http://localhost:11434.
 *
 * Usage:
 *   node compact-session.js <session.jsonl>
 *   node compact-session.js <session.jsonl> --threshold 30
 *   node compact-session.js <session.jsonl> --dry-run
 *
 * The script writes a new file alongside the input named
 * <name>.compacted.jsonl and never modifies the original.
 */

const fs   = require('fs');
const http = require('http');
const path = require('path');

const SUMMARY_PROMPT =
  'Summarize this conversation history concisely. ' +
  'Preserve: decisions made, open loops, facts learned, user preferences mentioned, task outcomes. ' +
  'Discard: pleasantries, repeated context, intermediate thinking steps.';

const OLLAMA_HOST  = 'localhost';
const OLLAMA_PORT  = 11434;
const OLLAMA_MODEL = 'gemma4:26b';

function parseArgs(argv) {
  const args = { file: null, threshold: 20, dryRun: false, model: OLLAMA_MODEL };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--dry-run') args.dryRun = true;
    else if (a === '--threshold') args.threshold = parseInt(argv[++i], 10);
    else if (a === '--model')     args.model     = argv[++i];
    else if (!args.file && !a.startsWith('--')) args.file = a;
  }
  if (!args.file) {
    console.error('Usage: compact-session.js <session.jsonl> [--threshold N] [--dry-run] [--model name]');
    process.exit(1);
  }
  if (Number.isNaN(args.threshold) || args.threshold < 1) {
    console.error('--threshold must be a positive integer');
    process.exit(1);
  }
  return args;
}

function readJsonl(file) {
  const raw = fs.readFileSync(file, 'utf-8');
  const turns = [];
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      turns.push(JSON.parse(trimmed));
    } catch (e) {
      console.error(`Skipping malformed line: ${trimmed.slice(0, 80)}...`);
    }
  }
  return turns;
}

function turnToText(turn) {
  // WormHole turns have user/assistant fields plus metadata.
  // Build a readable transcript chunk.
  const ts = turn.ts || '';
  const user = (turn.user || '').toString().trim();
  const asst = (turn.assistant || '').toString().trim();
  const parts = [];
  if (ts) parts.push(`[${ts}]`);
  if (user) parts.push(`USER: ${user}`);
  if (asst) parts.push(`ASSISTANT: ${asst}`);
  return parts.join('\n');
}

function callOllama(model, prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model,
      messages: [{ role: 'user', content: prompt }],
      stream: false
    });
    const req = http.request({
      hostname: OLLAMA_HOST,
      port:     OLLAMA_PORT,
      path:     '/api/chat',
      method:   'POST',
      headers: {
        'Content-Type':  'application/json',
        'Content-Length': Buffer.byteLength(body)
      },
      timeout: 600000
    }, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          return reject(new Error(`Ollama HTTP ${res.statusCode}: ${data.slice(0, 200)}`));
        }
        try {
          const parsed = JSON.parse(data);
          const content = parsed.message && parsed.message.content;
          if (!content) return reject(new Error(`Ollama response missing message.content: ${data.slice(0, 200)}`));
          resolve(content.trim());
        } catch (e) {
          reject(new Error(`Failed to parse Ollama response: ${e.message}`));
        }
      });
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(new Error('Ollama timeout (600s)')); });
    req.write(body);
    req.end();
  });
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const turns = readJsonl(args.file);

  if (turns.length <= args.threshold) {
    console.log(`Session has ${turns.length} turns; threshold is ${args.threshold}. Nothing to compact.`);
    return;
  }

  const oldTurns    = turns.slice(0, turns.length - args.threshold);
  const recentTurns = turns.slice(turns.length - args.threshold);

  const transcript = oldTurns.map(turnToText).filter(Boolean).join('\n\n');
  const fullPrompt = `${SUMMARY_PROMPT}\n\n---\n\n${transcript}`;

  if (args.dryRun) {
    console.log(`Would compact ${oldTurns.length} old turns into a summary, keeping the latest ${recentTurns.length}.`);
    console.log(`Approx summary input size: ${fullPrompt.length} chars`);
    console.log('First 3 turns that would be summarized:');
    oldTurns.slice(0, 3).forEach((t, i) => {
      console.log(`  ${i + 1}. ${turnToText(t).slice(0, 200).replace(/\n/g, ' | ')}...`);
    });
    return;
  }

  console.log(`Compacting ${oldTurns.length} old turns via Ollama (${args.model})...`);
  const summary = await callOllama(args.model, fullPrompt);

  const summaryTurn = {
    ts:          new Date().toISOString(),
    role:        'system',
    kind:        'compaction-summary',
    model:       args.model,
    covered:     oldTurns.length,
    covered_from: oldTurns[0] && oldTurns[0].ts || null,
    covered_to:   oldTurns[oldTurns.length - 1] && oldTurns[oldTurns.length - 1].ts || null,
    user:        '[compacted history]',
    assistant:   summary
  };

  const dir  = path.dirname(args.file);
  const base = path.basename(args.file, path.extname(args.file));
  const out  = path.join(dir, `${base}.compacted.jsonl`);

  const lines = [summaryTurn, ...recentTurns].map(t => JSON.stringify(t));
  fs.writeFileSync(out, lines.join('\n') + '\n');

  console.log(`Wrote ${out} (${lines.length} turns: 1 summary + ${recentTurns.length} recent).`);
}

main().catch(err => {
  console.error(err.stack || err.message || err);
  process.exit(1);
});
